services:
  - type: web
    name: mjpjay-website
    env: node
    buildCommand: npm run install:all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REACT_APP_API_URL
        value: https://mjpjay-website.onrender.com
    healthCheckPath: /api/test
    autoDeploy: true
    plan: free
